### ISSUE TITLE
Code of Conduct required

### ISSUE THREAD

**Issue by jessicaplant** [scottkellum/CJSS#12]
For a project as critical as this, it's important we establish a code of conduct to follow.

This must not become just another meme framework - it could become _the_ meme framework.

**Comment by KargJonas** [comment]
It will be the ultimate meme framework.

**Comment by scottkellum** [comment]
Reopening. This is important to me.

**Comment by KargJonas** [comment]
I've already added one :)

**Comment by scottkellum** [comment]
Ah awesome thank you! I’ll probably make some edits later

**Comment by KargJonas** [comment]
Alright :+1:
