### ISSUE TITLE
Create a plugin system

### ISSUE THREAD

**Issue by scottkellum** [scottkellum/CJSS#14]
Create a plugin system to allow users to add support for other languages. So you could add support for `--jsx`, `--scss`, `--pug`, `--sql` or whatever you want to parse, and if it should be parsed as markup, script, data, or style.

**Comment by cmcdaniels-ds** [comment]
` --sql`

( ͡ʘ ͜ʖ ͡ʘ)

**Comment by PatheticMustan** [comment]
`--php`
**pizza time stops**

**Comment by xsanda** [comment]
Parsing JSX looks like it's going to be hard: basically the only in-browser module available is [AnyWhichWay/jsxdirect](https://github.com/anywhichway/jsxdirect/), which is based on lots of regex and seems rather flimsy from a cursory glance over the code.

**Comment by KargJonas** [comment]
@xsanda https://github.com/KargJonas/live-jsx
