### ISSUE TITLE
eval is evil :(

### ISSUE THREAD

**Issue by KargJonas** [scottkellum/CJSS#7]

**Comment by scottkellum** [comment]
Is there any other option to evaluate strings as JS from CSS?

**Comment by PatheticMustan** [comment]
```Function()```?

**Comment by PatheticMustan** [comment]
Never mind. Function doesn't work... ;(

**Comment by xlf1024** [comment]
Probably e.g. using the function constructor. However, afaik, `eval` is considered evil because it executes strings as js, thus creating an additional way for malicious code to enter your site, so any other way of doing the same would't be better, just less readable.
However, for `--data` one could probably switch to `JSON.parse`, which does what you promise for `--data` without enabling code injection.

**Comment by KargJonas** [comment]
Well if you don't plan on using computed properties, I'd use JSON.parse for the data. JSON.parse gives you nice errors if you forget to close a string or stuff like that.

**Comment by xsanda** [comment]
Using the function constructor also allows you to specify `this`, rather than needing to perform a regex substitution.

**Comment by xsanda** [comment]
I've mostly fixed this in [KargJonas:#1](https://github.com/KargJonas/CJSS/pull/1), but I left `--data` as a globally evaluated JavaScript string.

How much of a breaking change would it be to downgrade data to just a plain old JSON object, given that the [documentation](https://github.com/scottkellum/CJSS/blob/master/README.md#data) does specify that it should be formatted as JSON? It's worth noting that the example is invalid JSON, as it uses single quotes.

**Comment by xsanda** [comment]
Not sure what the best way of ordering the pull requests is. My pull request to fix this ([KargJonas:#1](https://github.com/KargJonas/CJSS/pull/1)) builds upon #17, and also includes #18 (my fix for #15). If I create a pull request for my branch [xsanda:remove-eval](https://github.com/xsanda/CJSS/tree/remove-eval) here, merging it will also indirectly merge #17 and #18.

**Comment by KargJonas** [comment]
Honestly I've lost track of whats going on at this point.. I'll trust you to do the right thing. :sweat_smile:

**Comment by KargJonas** [comment]
`How much of a breaking change would it be to downgrade data to just a plain old JSON object, given that the documentation does specify that it should be formatted as JSON?`

That's the right thing to do. We should implement --computed for stuff that has to be evaluated..

**Comment by scottkellum** [comment]
> How much of a breaking change would it be to downgrade data to just a plain old JSON object

Y’all are being too serious here. This project should be treated like alpha software at the moment. Yes, it’s published, but with a warning that people shouldn’t use it. It’s also a very new technique and my JS skills are not particularly refined so this project requires plenty of polish.

**Comment by xsanda** [comment]
Ok. I wonder if we should change [data](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) to use native stored data for future use too?

**Comment by KargJonas** [comment]
So i was able to replace the "eval" for --js. #21

**Comment by scottkellum** [comment]
Closed with #21 . Thank you @KargJonas 🙏
