### ISSUE TITLE
add YAML support

### ISSUE THREAD

**Issue by vilchesalves** [scottkellum/CJSS#9]
Hello all.

I'm using CJSS for a few months in prod now and my life is definitely full of newfound joy.

I have a use case where I would like to generate the CJSS file on build time but my configuration is stored on a YAML file and, for the sake of practicality, I wouldn't like to parse it to JSON before appending it to the CJSS because that feels too much like a hack.

Cheers!

**Comment by scottkellum** [comment]
See issue #14

**Comment by xsanda** [comment]
[jeremyfa/yaml.js](https://github.com/jeremyfa/yaml.js) seems like a nice library for doing this, when a plugin system does appear.
